import * as fs from "node:fs";
import * as path from "node:path";
import {
  loadSpec,
  resolveRefName,
  getOperationsByTag,
  type OpenApiSpec,
  type SchemaObject,
  type OperationObject,
  type ParameterObject,
} from "./openapi.js";

// ─── Schema Generation ───────────────────────────────────────────────

/**
 * Generate validation schemas (Valibot or Zod) from OpenAPI component schemas.
 */
export async function generateSchemas(
  openapiPath: string,
  outputPath: string,
  framework: "svelte" | "react"
): Promise<{ success: boolean; schemaCount: number; outputPath: string }> {
  const spec = loadSpec(openapiPath);
  const schemas = spec.components?.schemas ?? {};
  const schemaNames = Object.keys(schemas);

  const lines: string[] = [];

  if (framework === "svelte") {
    lines.push('import * as v from "valibot";');
  } else {
    lines.push('import { z } from "zod";');
  }
  lines.push("");
  lines.push("// Auto-generated by gopilot-tools. Do not edit manually.");
  lines.push("");

  for (const [name, schema] of Object.entries(schemas)) {
    const schemaCode =
      framework === "svelte"
        ? generateValibotSchema(schema, schemas)
        : generateZodSchema(schema, schemas);

    if (framework === "svelte") {
      lines.push(`export type ${name} = v.InferOutput<typeof ${name}>;`);
      lines.push(`export const ${name} = ${schemaCode};`);
    } else {
      lines.push(`export const ${name} = ${schemaCode};`);
      lines.push(`export type ${name} = z.infer<typeof ${name}>;`);
    }
    lines.push("");
  }

  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(outputPath, lines.join("\n"));

  return { success: true, schemaCount: schemaNames.length, outputPath };
}

function generateValibotSchema(
  schema: SchemaObject,
  allSchemas: Record<string, SchemaObject>
): string {
  if (schema.$ref) {
    return resolveRefName(schema.$ref);
  }

  if (schema.allOf) {
    const parts = schema.allOf.map((s) => generateValibotSchema(s, allSchemas));
    if (parts.length === 1) return parts[0];
    return `v.intersect([${parts.join(", ")}])`;
  }

  if (schema.oneOf) {
    const parts = schema.oneOf.map((s) => generateValibotSchema(s, allSchemas));
    return `v.union([${parts.join(", ")}])`;
  }

  if (schema.enum) {
    const values = schema.enum.map((e) => `"${e}"`).join(", ");
    return `v.picklist([${values}])`;
  }

  switch (schema.type) {
    case "string": {
      const pipes: string[] = ["v.string()"];
      if (schema.minLength !== undefined) pipes.push(`v.minLength(${schema.minLength})`);
      if (schema.maxLength !== undefined) pipes.push(`v.maxLength(${schema.maxLength})`);
      if (schema.pattern) pipes.push(`v.regex(/${schema.pattern}/)`);
      if (schema.format === "email") pipes.push('v.email()');
      if (schema.format === "uri" || schema.format === "url") pipes.push('v.url()');
      return pipes.length > 1 ? `v.pipe(${pipes.join(", ")})` : pipes[0];
    }

    case "number":
    case "integer": {
      const base = schema.type === "integer" ? "v.pipe(v.number(), v.integer())" : "v.number()";
      const pipes: string[] = [];
      if (schema.minimum !== undefined) pipes.push(`v.minValue(${schema.minimum})`);
      if (schema.maximum !== undefined) pipes.push(`v.maxValue(${schema.maximum})`);
      if (pipes.length === 0) return base;
      if (schema.type === "integer") {
        return `v.pipe(v.number(), v.integer(), ${pipes.join(", ")})`;
      }
      return `v.pipe(v.number(), ${pipes.join(", ")})`;
    }

    case "boolean":
      return "v.boolean()";

    case "array": {
      const itemSchema = schema.items
        ? generateValibotSchema(schema.items, allSchemas)
        : "v.unknown()";
      const base = `v.array(${itemSchema})`;
      const pipes: string[] = [];
      if (schema.minItems !== undefined) pipes.push(`v.minLength(${schema.minItems})`);
      if (schema.maxItems !== undefined) pipes.push(`v.maxLength(${schema.maxItems})`);
      return pipes.length > 0 ? `v.pipe(${base}, ${pipes.join(", ")})` : base;
    }

    case "object": {
      if (!schema.properties) return "v.record(v.string(), v.unknown())";
      const required = new Set(schema.required ?? []);
      const props = Object.entries(schema.properties).map(([key, prop]) => {
        const propSchema = generateValibotSchema(prop, allSchemas);
        const isRequired = required.has(key);
        return `  ${key}: ${isRequired ? propSchema : `v.optional(${propSchema})`}`;
      });
      return `v.object({\n${props.join(",\n")},\n})`;
    }

    default:
      return "v.unknown()";
  }
}

function generateZodSchema(
  schema: SchemaObject,
  allSchemas: Record<string, SchemaObject>
): string {
  if (schema.$ref) {
    return resolveRefName(schema.$ref);
  }

  if (schema.allOf) {
    const parts = schema.allOf.map((s) => generateZodSchema(s, allSchemas));
    if (parts.length === 1) return parts[0];
    return parts.reduce((acc, part) => `${acc}.merge(${part})`);
  }

  if (schema.oneOf) {
    const parts = schema.oneOf.map((s) => generateZodSchema(s, allSchemas));
    return `z.union([${parts.join(", ")}])`;
  }

  if (schema.enum) {
    const values = schema.enum.map((e) => `"${e}"`).join(", ");
    return `z.enum([${values}])`;
  }

  switch (schema.type) {
    case "string": {
      let chain = "z.string()";
      if (schema.minLength !== undefined) chain += `.min(${schema.minLength})`;
      if (schema.maxLength !== undefined) chain += `.max(${schema.maxLength})`;
      if (schema.pattern) chain += `.regex(/${schema.pattern}/)`;
      if (schema.format === "email") chain += ".email()";
      if (schema.format === "uri" || schema.format === "url") chain += ".url()";
      return chain;
    }

    case "number":
    case "integer": {
      let chain = "z.number()";
      if (schema.type === "integer") chain += ".int()";
      if (schema.minimum !== undefined) chain += `.min(${schema.minimum})`;
      if (schema.maximum !== undefined) chain += `.max(${schema.maximum})`;
      return chain;
    }

    case "boolean":
      return "z.boolean()";

    case "array": {
      const itemSchema = schema.items
        ? generateZodSchema(schema.items, allSchemas)
        : "z.unknown()";
      let chain = `z.array(${itemSchema})`;
      if (schema.minItems !== undefined) chain += `.min(${schema.minItems})`;
      if (schema.maxItems !== undefined) chain += `.max(${schema.maxItems})`;
      return chain;
    }

    case "object": {
      if (!schema.properties) return "z.record(z.string(), z.unknown())";
      const required = new Set(schema.required ?? []);
      const props = Object.entries(schema.properties).map(([key, prop]) => {
        const propSchema = generateZodSchema(prop, allSchemas);
        const isRequired = required.has(key);
        return `  ${key}: ${isRequired ? propSchema : `${propSchema}.optional()`}`;
      });
      return `z.object({\n${props.join(",\n")},\n})`;
    }

    default:
      return "z.unknown()";
  }
}

// ─── Remote Function Generation ──────────────────────────────────────

/**
 * Generate typed remote functions from OpenAPI operations.
 */
export async function generateRemotes(
  openapiPath: string,
  outputDir: string,
  schemasImportPath: string,
  framework: "svelte" | "react"
): Promise<{ success: boolean; fileCount: number; files: string[] }> {
  const spec = loadSpec(openapiPath);
  const operationsByTag = getOperationsByTag(spec);
  const schemas = spec.components?.schemas ?? {};

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const SKIP_TAGS = new Set(["Auth", "System", "Internal", "WebSocket"]);
  const generatedFiles: string[] = [];

  for (const [tag, operations] of operationsByTag) {
    if (SKIP_TAGS.has(tag)) continue;

    const fileName = tagToFileName(tag, framework);
    const filePath = path.join(outputDir, fileName);

    const content = framework === "svelte"
      ? generateSvelteRemote(tag, operations, schemasImportPath, schemas)
      : generateReactRemote(tag, operations, schemasImportPath, schemas);

    fs.writeFileSync(filePath, content);
    generatedFiles.push(fileName);
  }

  // Generate barrel index
  const indexLines = [
    "// Auto-generated by gopilot-tools. Do not edit manually.",
    "",
  ];
  for (const file of generatedFiles) {
    const moduleName = file.replace(/\.(remote|server)\.ts$/, "");
    indexLines.push(
      `export * from "./${moduleName}.${framework === "svelte" ? "remote" : "server"}";`
    );
  }
  fs.writeFileSync(path.join(outputDir, "index.ts"), indexLines.join("\n") + "\n");
  generatedFiles.push("index.ts");

  // Generate GUIDE.md
  const guideLines = [
    "# SDK Remote Functions Guide",
    "",
    "Auto-generated by gopilot-tools. Do not edit manually.",
    "",
    "| Function | Method | Path | Tag |",
    "|----------|--------|------|-----|",
  ];
  for (const [tag, operations] of operationsByTag) {
    if (SKIP_TAGS.has(tag)) continue;
    for (const { method, path: opPath, operation } of operations) {
      const funcName = operationIdToFuncName(operation.operationId ?? `${method}-${opPath}`);
      guideLines.push(`| ${funcName} | ${method.toUpperCase()} | ${opPath} | ${tag} |`);
    }
  }
  fs.writeFileSync(path.join(outputDir, "GUIDE.md"), guideLines.join("\n") + "\n");
  generatedFiles.push("GUIDE.md");

  return { success: true, fileCount: generatedFiles.length, files: generatedFiles };
}

function generateSvelteRemote(
  tag: string,
  operations: Array<{ method: string; path: string; operation: OperationObject }>,
  schemasImportPath: string,
  allSchemas: Record<string, SchemaObject>
): string {
  const imports = new Set<string>();
  const lines: string[] = [];

  lines.push('import { query, command } from "$app/server";');
  lines.push('import * as v from "valibot";');
  lines.push(`import { goApi } from "$lib/server/go-client";`);
  lines.push("");
  lines.push("// Auto-generated by gopilot-tools. Do not edit manually.");
  lines.push("");

  for (const { method, path: opPath, operation } of operations) {
    const funcName = operationIdToFuncName(operation.operationId ?? `${method}-${opPath}`);
    const isRead = method.toLowerCase() === "get";
    const wrapperType = isRead ? "query" : "command";

    // Collect type imports
    const typeImports = collectTypeImports(operation, allSchemas);
    for (const t of typeImports) imports.add(t);

    // Build params schema for query params
    const queryParams = (operation.parameters ?? []).filter((p) => p.in === "query");
    const pathParams = (operation.parameters ?? []).filter((p) => p.in === "path");

    // Get request body schema
    const bodyRef = getRequestBodyRef(operation);
    const responseRef = getSuccessResponseRef(operation);

    if (isRead) {
      // query() function
      const paramSchema = queryParams.length > 0
        ? buildValibotParamsSchema(queryParams)
        : null;

      lines.push(`export const ${funcName} = ${wrapperType}(`);
      if (paramSchema) {
        lines.push(`  v.optional(${paramSchema}),`);
        const paramNames = queryParams.map((p) => p.name).join(", ");
        lines.push(`  async ({ ${paramNames} } = {}) => {`);
      } else {
        lines.push("  async () => {");
      }

      const typedResponse = responseRef ? `<${responseRef}>` : "";
      const apiPath = buildTemplatePath(opPath, pathParams);
      const paramsArg = queryParams.length > 0
        ? `, { params: { ${queryParams.map((p) => p.name).join(", ")} } }`
        : "";

      lines.push(`    return goApi.get${typedResponse}(${apiPath}${paramsArg});`);
      lines.push("  }");
      lines.push(");");
    } else {
      // command() function
      const bodySchemaName = bodyRef;

      if (bodySchemaName) {
        lines.push(`export const ${funcName} = ${wrapperType}(`);
        lines.push(`  ${bodySchemaName},`);
        lines.push(`  async (body) => {`);
      } else {
        lines.push(`export const ${funcName} = ${wrapperType}(`);
        lines.push("  async () => {");
      }

      const typedResponse = responseRef ? `<${responseRef}>` : "";
      const apiPath = buildTemplatePath(opPath, pathParams);
      const methodName = method.toLowerCase() === "delete" ? "del" : method.toLowerCase();
      const bodyArg = bodySchemaName ? ", body" : "";

      lines.push(
        `    return goApi.${methodName}${typedResponse}(${apiPath}${bodyArg});`
      );
      lines.push("  }");
      lines.push(");");
    }
    lines.push("");
  }

  // Add schema imports at the top
  if (imports.size > 0) {
    const importLine = `import type { ${[...imports].sort().join(", ")} } from "${schemasImportPath}";`;
    lines.splice(3, 0, importLine);
  }

  return lines.join("\n") + "\n";
}

function generateReactRemote(
  tag: string,
  operations: Array<{ method: string; path: string; operation: OperationObject }>,
  schemasImportPath: string,
  allSchemas: Record<string, SchemaObject>
): string {
  const imports = new Set<string>();
  const schemaImports = new Set<string>();
  const lines: string[] = [];

  lines.push('"use server";');
  lines.push("");
  lines.push(`import { goApi } from "@/lib/go-client";`);
  lines.push("");
  lines.push("// Auto-generated by gopilot-tools. Do not edit manually.");
  lines.push("");

  for (const { method, path: opPath, operation } of operations) {
    const funcName = operationIdToFuncName(operation.operationId ?? `${method}-${opPath}`);

    const queryParams = (operation.parameters ?? []).filter((p) => p.in === "query");
    const pathParams = (operation.parameters ?? []).filter((p) => p.in === "path");

    const bodyRef = getRequestBodyRef(operation);
    const responseRef = getSuccessResponseRef(operation);

    if (bodyRef) {
      schemaImports.add(bodyRef);
    }
    if (responseRef) {
      imports.add(responseRef);
    }

    const typeImports = collectTypeImports(operation, allSchemas);
    for (const t of typeImports) imports.add(t);

    const isRead = method.toLowerCase() === "get";

    if (isRead) {
      // Async function for reads
      const paramsType = queryParams.length > 0
        ? `params?: { ${queryParams.map((p) => `${p.name}?: ${tsTypeFromParam(p)}`).join("; ")} }`
        : "";
      const returnType = responseRef ? `: Promise<${responseRef}>` : "";

      lines.push(`export async function ${funcName}(${paramsType})${returnType} {`);

      const typedResponse = responseRef ? `<${responseRef}>` : "";
      const apiPath = buildTemplatePath(opPath, pathParams);
      const paramsArg = queryParams.length > 0 ? ", { params }" : "";

      lines.push(`  return goApi.get${typedResponse}(${apiPath}${paramsArg});`);
      lines.push("}");
    } else {
      // Server action for mutations
      if (bodyRef) {
        lines.push(
          `export async function ${funcName}(input: z.infer<typeof ${bodyRef}>) {`
        );
        lines.push(`  const body = ${bodyRef}.parse(input);`);
      } else {
        lines.push(`export async function ${funcName}() {`);
      }

      const typedResponse = responseRef ? `<${responseRef}>` : "";
      const apiPath = buildTemplatePath(opPath, pathParams);
      const methodName = method.toLowerCase() === "delete" ? "del" : method.toLowerCase();
      const bodyArg = bodyRef ? ", body" : "";

      lines.push(
        `  return goApi.${methodName}${typedResponse}(${apiPath}${bodyArg});`
      );
      lines.push("}");
    }
    lines.push("");
  }

  // Add imports
  const importLines: string[] = [];
  if (schemaImports.size > 0) {
    importLines.push('import { z } from "zod";');
    const allImports = new Set([...imports, ...schemaImports]);
    const typeOnly = [...imports].filter((i) => !schemaImports.has(i));
    const valueImports = [...schemaImports];

    if (typeOnly.length > 0 && valueImports.length > 0) {
      importLines.push(
        `import { ${valueImports.sort().join(", ")}, type ${typeOnly.sort().join(", type ")} } from "${schemasImportPath}";`
      );
    } else if (valueImports.length > 0) {
      importLines.push(
        `import { ${valueImports.sort().join(", ")} } from "${schemasImportPath}";`
      );
    } else if (typeOnly.length > 0) {
      importLines.push(
        `import type { ${typeOnly.sort().join(", ")} } from "${schemasImportPath}";`
      );
    }
  } else if (imports.size > 0) {
    importLines.push(
      `import type { ${[...imports].sort().join(", ")} } from "${schemasImportPath}";`
    );
  }

  if (importLines.length > 0) {
    lines.splice(2, 0, ...importLines);
  }

  return lines.join("\n") + "\n";
}

// ─── Helpers ─────────────────────────────────────────────────────────

function tagToFileName(tag: string, framework: "svelte" | "react"): string {
  const kebab = tag
    .replace(/([a-z])([A-Z])/g, "$1-$2")
    .toLowerCase()
    .replace(/\s+/g, "-");
  return framework === "svelte" ? `${kebab}.remote.ts` : `${kebab}.server.ts`;
}

function operationIdToFuncName(operationId: string): string {
  return operationId
    .replace(/-([a-z])/g, (_, c) => c.toUpperCase())
    .replace(/^([A-Z])/, (_, c) => c.toLowerCase());
}

function getRequestBodyRef(operation: OperationObject): string | null {
  const content = operation.requestBody?.content;
  if (!content) return null;

  const jsonContent = content["application/json"];
  if (!jsonContent?.schema) return null;

  if ("$ref" in jsonContent.schema && jsonContent.schema.$ref) {
    return resolveRefName(jsonContent.schema.$ref);
  }
  return null;
}

function getSuccessResponseRef(operation: OperationObject): string | null {
  const responses = operation.responses;
  if (!responses) return null;

  const successResponse = responses["200"] ?? responses["201"];
  if (!successResponse?.content) return null;

  const jsonContent = successResponse.content["application/json"];
  if (!jsonContent?.schema) return null;

  if ("$ref" in jsonContent.schema && jsonContent.schema.$ref) {
    return resolveRefName(jsonContent.schema.$ref);
  }
  return null;
}

function collectTypeImports(
  operation: OperationObject,
  allSchemas: Record<string, SchemaObject>
): string[] {
  const types: string[] = [];

  const bodyRef = getRequestBodyRef(operation);
  if (bodyRef) types.push(bodyRef);

  const responseRef = getSuccessResponseRef(operation);
  if (responseRef) types.push(responseRef);

  return types;
}

function buildValibotParamsSchema(params: ParameterObject[]): string {
  const fields = params.map((p) => {
    let type = "v.string()";
    if (p.schema?.type === "number" || p.schema?.type === "integer") {
      type = "v.number()";
    } else if (p.schema?.type === "boolean") {
      type = "v.boolean()";
    }
    return `    ${p.name}: v.optional(${type})`;
  });
  return `v.object({\n${fields.join(",\n")},\n  })`;
}

function buildTemplatePath(
  opPath: string,
  pathParams: ParameterObject[]
): string {
  if (pathParams.length === 0) {
    return `"${opPath}"`;
  }
  // Convert /api/v1/items/{id} to template literal
  const template = opPath.replace(
    /\{(\w+)\}/g,
    (_, name) => `\${${name}}`
  );
  return `\`${template}\``;
}

function tsTypeFromParam(param: ParameterObject): string {
  switch (param.schema?.type) {
    case "number":
    case "integer":
      return "number";
    case "boolean":
      return "boolean";
    default:
      return "string";
  }
}
